### PR TITLE
Update version to 0.1.1

### PR DESCRIPTION
**Pull request by aappoalander**
### Features
- Updates for dependencies 
- Fix for minified code examples in Icon documentation

### CODE REVIEW

**Comment by ketsappi** [comment]
Just small note, but might be good idea to have the PR name to be like in others when updating version by releasing.
So I'll suggest PR name to be in this case **Release/0.1.1**

*I also added the **release** label for this repo as it was in the suomifi-ui-components -repo and added it to this PR*

**Comment by aappoalander** [comment]
> Just small note, but might be good idea to have the PR name to be like in others when updating version by releasing.
> So I'll suggest PR name to be in this case **Release/0.1.1**

I'd rather have the names without the slash, e.g. Release 0.1.1, but that is a minor detail. Naming the releases however should communicate the contents better. The scope of these PR's is actually only to increase the version number, but the scope of the release is more than Version x.x.x. => Most relevant change / changes could be communicated in the name of the version.

**Comment by ketsappi** [comment]
> The scope of these PR's is actually only to increase the version number, but the scope of the release is more than Version x.x.x. => Most relevant change / changes could be communicated in the name of the version.

I think it might be confusing that the name has some most relevant change(s), but then when reviewer looks the commits and file change, only the version increase can be seen.

And maybe the release notes will answer what the release has in it as a whole.

**The current name of this PR then probably describes the situation best without any change**. We should just make other PR names then clearly different in cases e.g we update some version of some dependency to prevent confusion.

**Comment by aappoalander** [comment]
> I think it might be confusing that the name has some most relevant change(s), but then when reviewer looks the commits and file change, only the version increase can be seen.

I did not mean to refer to the version increase PR name, but the actual release name that is coupled with the tag and release notes. Now the releases only state v.0.1.0 which does not tell anything to the reader - at least in my opinion.

**Comment by ketsappi** [comment]
> I did not mean to refer to the version increase PR name, but the actual release name that is coupled with the tag and release notes. Now the releases only state v.0.1.0 which does not tell anything to the reader - at least in my opinion.

I would also like to see that release names to be more "unique"/informative.

**Pull request closed without merging**
